import type { HuoziFormat } from "./detect-format";
import type { TabEntry } from "./extract-tabs";

export interface HtmlIframeDocumentInput {
  /** Sanitized HTML body generated by processHtmlDirect/processChartComponents. */
  html: string;
  /** Detected format, passed into the iframe as document metadata. */
  format: HuoziFormat;
  /** Dashboard tabs extracted from the source document. */
  tabs?: TabEntry[];
  /** Dashboard auto-refresh interval. */
  refreshMs?: number | null;
}

function escapeScriptEnd(source: string): string {
  return source.replace(/<\/script/gi, "<\\/script");
}

function bridgeScript(input: HtmlIframeDocumentInput): string {
  const tabs = JSON.stringify(input.tabs ?? []);
  const refreshMs = input.refreshMs && input.refreshMs > 0 ? input.refreshMs : 0;

  return `(function(){
  var TABS = ${tabs};
  var REFRESH_MS = ${refreshMs};
  var activeTab = null;
  var initTabs = Object.create(null);

  function post(type, detail) {
    try {
      parent.postMessage({ source: 'huozi-frame', type: type, detail: detail || {} }, '*');
    } catch (_) {}
  }

  function ensureBus() {
    var bus = (window.huozi = window.huozi || {});
    var listeners = (bus.__listeners = bus.__listeners || Object.create(null));
    if (typeof bus.on !== 'function') {
      bus.on = function(name, fn) {
        if (!listeners[name]) listeners[name] = [];
        listeners[name].push(fn);
        return function() { bus.off && bus.off(name, fn); };
      };
    }
    if (typeof bus.off !== 'function') {
      bus.off = function(name, fn) {
        var arr = listeners[name];
        if (!arr) return;
        listeners[name] = arr.filter(function(item) { return item !== fn; });
      };
    }
    if (typeof bus.emit !== 'function') {
      bus.emit = function(name, detail) {
        var arr = listeners[name] || [];
        arr.slice().forEach(function(fn) {
          try { fn(detail); } catch (err) { setTimeout(function(){ throw err; }, 0); }
        });
      };
    }
    bus.tabs = TABS;
    bus.activeTab = activeTab;
    bus.goPage = goPage;
    bus.goTab = function(id) { goTab(id, 'show'); };
    bus.refresh = refresh;
    return bus;
  }

  function emitHuozi(name, detail) {
    var bus = ensureBus();
    if (typeof bus.emit === 'function') bus.emit(name, detail);
  }

  function postSize() {
    var root = document.documentElement;
    var body = document.body;
    var height = Math.max(
      root ? root.scrollHeight : 0,
      body ? body.scrollHeight : 0,
      root ? root.offsetHeight : 0,
      body ? body.offsetHeight : 0
    );
    post('resize', { height: height });
  }

  function goPage(id) {
    if (!id) return;
    var el = document.getElementById(id);
    if (!el) return;
    el.scrollIntoView({ behavior: 'smooth', block: 'start', inline: 'start' });
    post('page:changed', { pageId: id });
  }

  function initPageObserver() {
    var pages = Array.prototype.slice.call(document.querySelectorAll('[data-page][id]'));
    if (pages.length < 2 || typeof IntersectionObserver === 'undefined') return;
    var observer = new IntersectionObserver(function(entries) {
      var best = null;
      entries.forEach(function(entry) {
        if (!entry.isIntersecting) return;
        if (!best || entry.intersectionRatio > best.intersectionRatio) best = entry;
      });
      if (best && best.target && best.target.id) post('page:changed', { pageId: best.target.id });
    }, { threshold: [0.45, 0.7, 0.95] });
    pages.forEach(function(page) { observer.observe(page); });
  }

  function tabExists(id) {
    return TABS.some(function(tab) { return tab.id === id; });
  }

  function goTab(id, reason) {
    if (!id || !tabExists(id)) return;
    activeTab = id;
    var dashboard = document.querySelector('.huozi-dashboard') || document.body;
    if (dashboard && dashboard.classList) dashboard.classList.add('huozi-has-tabs');
    Array.prototype.slice.call(document.querySelectorAll('[data-tab]')).forEach(function(el) {
      var isActive = el.getAttribute('data-tab') === id;
      el.classList.toggle('is-active', isActive);
      el.toggleAttribute('hidden', !isActive);
    });
    var bus = ensureBus();
    bus.activeTab = id;
    var first = !initTabs[id];
    initTabs[id] = true;
    var detail = { tabId: id, reason: reason || (first ? 'init' : 'show') };
    emitHuozi('tab', detail);
    post('tab:changed', detail);
    try { window.dispatchEvent(new Event('resize')); } catch (_) {}
    postSize();
  }

  function initTabState() {
    if (!TABS.length) return;
    var hash = (window.location.hash || '').replace(/^#/, '');
    goTab(tabExists(hash) ? hash : TABS[0].id, 'init');
    if (REFRESH_MS > 0) {
      window.setInterval(refresh, REFRESH_MS);
    }
  }

  function refresh() {
    var tabId = activeTab || (TABS[0] && TABS[0].id) || null;
    if (tabId) {
      var detail = { tabId: tabId, reason: 'refresh' };
      emitHuozi('tab', detail);
      post('tab:changed', detail);
    }
    post('refresh', { tabId: tabId });
  }

  ensureBus();

  window.addEventListener('message', function(event) {
    var data = event.data || {};
    if (data.source !== 'huozi-host') return;
    var detail = data.detail || {};
    if (data.type === 'page:go') goPage(detail.pageId);
    if (data.type === 'tab:go') goTab(detail.tabId, detail.reason || 'show');
    if (data.type === 'refresh') refresh();
  });

  document.addEventListener('DOMContentLoaded', function() {
    ensureBus();
    initPageObserver();
    initTabState();
    post('ready', { format: '${input.format}' });
    postSize();
    if (typeof ResizeObserver !== 'undefined') {
      var ro = new ResizeObserver(postSize);
      ro.observe(document.documentElement);
      if (document.body) ro.observe(document.body);
    }
  });
})();`;
}

export function buildHtmlIframeSrcDoc(input: HtmlIframeDocumentInput): string {
  const format = input.format.replace(/"/g, "");
  const bridge = escapeScriptEnd(bridgeScript(input));

  return `<!doctype html>
<html data-huozi-frame="1" data-huozi-format="${format}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <base target="_blank">
  <style>
    html, body { width: 100%; min-height: 100%; margin: 0; }
    body { overflow: auto; }
    [data-tab][hidden] { display: none !important; }
  </style>
  <script>${bridge}</script>
</head>
<body>
${input.html}
</body>
</html>`;
}
