#!/usr/bin/env bash
#
# scripts/edge-deploy.sh
#
# One-shot deploy of the huozi Edge edition into the user's Cloudflare
# account. Deploys TWO workers (matches the cloud architecture):
#
#   1. huozi-edge        — cloud worker (D1 / R2 / DOs / MCP / auth APIs)
#   2. huozi-edge-app    — main Next.js worker (login, /workspace, /p,
#                          /api BFF). Talks to (1) via service binding.
#
# Both run on workers.dev URLs by default (no custom domain). Re-runs are
# idempotent: D1 / R2 reuse existing rows, secrets are rotated, workers
# are redeployed.
#
# Provisions:
#   - Worker (cloud):   huozi-edge
#   - Worker (main):    huozi-edge-app
#   - D1:               huozi-edge-db
#   - R2:               huozi-edge-blobs
#   - DOs:              HuoziWorkspaceDO, HuoziSessionDO (on cloud worker)
#   - Service binding:  huozi-edge-app.CLOUD → huozi-edge
#   - Secrets:          HUOZI_ADMIN_SECRET, HUOZI_AUTH_SECRET (on both),
#                       HUOZI_PUBLIC_BASE (on cloud)
#   - Workspace row + first admin api_key
#
# After it finishes you'll get:
#   - The main worker URL  (https://huozi-edge-app.<acct>.workers.dev)
#     ← visit this in a browser to use the product
#   - The cloud worker URL (https://huozi-edge.<acct>.workers.dev)
#     ← /mcp endpoint that Agents talk to
#   - The bootstrap api_key (paste at /workspace/connect)
#   - .huozi-edge.env file (for local `npm run dev` against this stack)
#
# Usage:
#   scripts/edge-deploy.sh
#   WORKSPACE_SLUG=alice scripts/edge-deploy.sh
#
# Tear down: scripts/edge-teardown.sh
#

set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKER_DIR="$ROOT_DIR/packages/huozi-cloud"

WORKSPACE_SLUG="${WORKSPACE_SLUG:-default}"
WORKSPACE_NAME="${WORKSPACE_NAME:-huozi-edge}"
ADMIN_USER_ID="${ADMIN_USER_ID:-admin}"

if [[ ! "$WORKSPACE_SLUG" =~ ^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$ ]]; then
  echo "✗ WORKSPACE_SLUG must match /^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$/  (got: $WORKSPACE_SLUG)" >&2
  exit 1
fi

CLOUD_WORKER_NAME="huozi-edge"
MAIN_WORKER_NAME="huozi-edge-app"
D1_NAME="huozi-edge-db"
R2_NAME="huozi-edge-blobs"
CLOUD_WRANGLER_TOML="$WORKER_DIR/wrangler.edge.toml"
MAIN_WRANGLER_JSONC="$ROOT_DIR/wrangler.edge.jsonc"
ENV_FILE="$ROOT_DIR/.huozi-edge.env"

cyan() { printf '\033[36m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*" >&2; }

# ── Preflight ────────────────────────────────────────────────────────────
cyan "▸ Preflight"
command -v node >/dev/null || { red "✗ node not in PATH"; exit 1; }
command -v npx >/dev/null || { red "✗ npx not in PATH"; exit 1; }
command -v jq >/dev/null || { red "✗ jq not in PATH (brew install jq)"; exit 1; }

cd "$WORKER_DIR"
npx wrangler whoami >/dev/null 2>&1 || {
  red "✗ wrangler not authenticated. Run \`npx wrangler login\` first."
  exit 1
}

# ── Generate auth secrets up-front (need them on both workers) ──────────
ADMIN_SECRET="$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')"
AUTH_SECRET="$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')"
SIGNING_SECRET="$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')"

# ╔════════════════════════════════════════════════════════════════════╗
# ║  STAGE 1: Cloud worker (huozi-edge)                                ║
# ╚════════════════════════════════════════════════════════════════════╝

# ── Build cloud worker ───────────────────────────────────────────────────
cyan "▸ Building cloud worker (tsc → dist/)"
npx tsc

# ── Generate cloud wrangler.toml ─────────────────────────────────────────
cyan "▸ Generating $(basename "$CLOUD_WRANGLER_TOML")"
cat > "$CLOUD_WRANGLER_TOML" <<EOF
# Auto-generated by scripts/edge-deploy.sh — DO NOT EDIT BY HAND.
# Tear down:  scripts/edge-teardown.sh
name = "$CLOUD_WORKER_NAME"
main = "dist/worker/index.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

# No custom domain — uses the workers.dev URL so we don't touch DNS.

[[r2_buckets]]
binding = "BLOBS"
bucket_name = "$R2_NAME"

[[d1_databases]]
binding = "DB"
database_name = "$D1_NAME"
database_id = "__FILLED_AFTER_CREATE__"

[[durable_objects.bindings]]
name = "WORKSPACE_DO"
class_name = "HuoziWorkspaceDO"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "HuoziSessionDO"

[[migrations]]
tag = "v1"
new_classes = ["HuoziWorkspaceDO", "HuoziSessionDO"]

# Weekly R2 orphan-blob GC. See src/storage/cloudflare/blob-gc.ts.
[triggers]
crons = ["0 4 * * SUN"]

[observability]
enabled = true
EOF

# ── Create / find D1 ─────────────────────────────────────────────────────
cyan "▸ Creating D1 database $D1_NAME"
npx wrangler d1 create "$D1_NAME" 2>&1 | tail -3 || true
D1_ID="$(npx wrangler d1 list --json 2>/dev/null \
         | jq -r --arg n "$D1_NAME" '.[] | select(.name==$n) | .uuid' \
         | head -1 || true)"
if [[ -z "$D1_ID" ]]; then
  red "✗ Failed to create or find D1 $D1_NAME"
  exit 1
fi
green "  database_id = $D1_ID"
sed -i.bak "s|__FILLED_AFTER_CREATE__|$D1_ID|" "$CLOUD_WRANGLER_TOML" && rm -f "$CLOUD_WRANGLER_TOML.bak"

# ── Create R2 (idempotent) ───────────────────────────────────────────────
cyan "▸ Creating R2 bucket $R2_NAME"
npx wrangler r2 bucket create "$R2_NAME" 2>&1 | grep -v "already exists" || true

# ── Apply schema ─────────────────────────────────────────────────────────
cyan "▸ Applying D1 schema"
npx wrangler d1 execute "$D1_NAME" --remote \
  --config "$CLOUD_WRANGLER_TOML" \
  --file src/storage/cloudflare/schema.sql >/dev/null

# ── Seed admin user / workspace / membership ─────────────────────────────
cyan "▸ Seeding admin user / workspace / membership rows"
NOW_MS=$(node -e 'process.stdout.write(String(Date.now()))')
WORKSPACE_UUID=$(node -e 'process.stdout.write(require("crypto").randomUUID())')
SEED_SQL=$(cat <<SQL
INSERT OR IGNORE INTO users (id, email, display_name, created_at)
  VALUES ('$ADMIN_USER_ID', 'admin@edge.local', 'Edge Admin', $NOW_MS);
INSERT OR IGNORE INTO workspaces (id, slug, name, owner_id, created_at)
  VALUES ('$WORKSPACE_UUID', '$WORKSPACE_SLUG', '$WORKSPACE_NAME', '$ADMIN_USER_ID', $NOW_MS);
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, joined_at)
  VALUES ('$WORKSPACE_UUID', '$ADMIN_USER_ID', 'owner', $NOW_MS);
SQL
)
npx wrangler d1 execute "$D1_NAME" --remote \
  --config "$CLOUD_WRANGLER_TOML" \
  --command "$SEED_SQL" >/dev/null

# ── Push secrets to cloud worker ─────────────────────────────────────────
cyan "▸ Pushing secrets to cloud worker"
echo "$ADMIN_SECRET"   | npx wrangler secret put HUOZI_ADMIN_SECRET   --config "$CLOUD_WRANGLER_TOML" >/dev/null
echo "$AUTH_SECRET"    | npx wrangler secret put HUOZI_AUTH_SECRET    --config "$CLOUD_WRANGLER_TOML" >/dev/null
echo "$SIGNING_SECRET" | npx wrangler secret put HUOZI_SIGNING_SECRET --config "$CLOUD_WRANGLER_TOML" >/dev/null

# ── Deploy cloud worker ──────────────────────────────────────────────────
cyan "▸ Deploying cloud worker"
CLOUD_DEPLOY_OUT="$(npx wrangler deploy --config "$CLOUD_WRANGLER_TOML" 2>&1 || true)"
CLOUD_WORKER_URL="$(echo "$CLOUD_DEPLOY_OUT" | grep -Eo 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -1 || true)"
if [[ -z "$CLOUD_WORKER_URL" ]]; then
  red "✗ Couldn't extract cloud worker URL from deploy output"
  echo "$CLOUD_DEPLOY_OUT"
  exit 1
fi
green "  Cloud worker: $CLOUD_WORKER_URL"

# ╔════════════════════════════════════════════════════════════════════╗
# ║  STAGE 2: Main Next.js worker (huozi-edge-app)                     ║
# ╚════════════════════════════════════════════════════════════════════╝

# ── Generate main wrangler config ────────────────────────────────────────
cyan "▸ Generating $(basename "$MAIN_WRANGLER_JSONC")"
cat > "$MAIN_WRANGLER_JSONC" <<JSONC
// Auto-generated by scripts/edge-deploy.sh — DO NOT EDIT BY HAND.
// Tear down:  scripts/edge-teardown.sh
{
  "\$schema": "node_modules/wrangler/config-schema.json",
  "main": ".open-next/worker.js",
  "name": "$MAIN_WORKER_NAME",
  "compatibility_date": "2025-04-01",
  "compatibility_flags": ["nodejs_compat"],
  "assets": {
    "directory": ".open-next/assets",
    "binding": "ASSETS"
  },
  "workers_dev": true,
  "services": [
    { "binding": "CLOUD", "service": "$CLOUD_WORKER_NAME" }
  ],
  "vars": {
    "HUOZI_EDITION": "edge",
    "HUOZI_EDGE_WORKSPACE_SLUG": "$WORKSPACE_SLUG"
  }
}
JSONC

# ── Build Next.js with OpenNext ──────────────────────────────────────────
cyan "▸ Building Next.js (OpenNext, HUOZI_EDITION=edge)"
cd "$ROOT_DIR"
HUOZI_EDITION=edge npx @opennextjs/cloudflare build > /tmp/huozi-edge-opennext-build.log 2>&1 || {
  red "✗ OpenNext build failed. Tail of log:"
  tail -20 /tmp/huozi-edge-opennext-build.log >&2
  exit 1
}

# ── Push secrets to main worker (must exist before deploy that references them) ──
cyan "▸ Pushing secrets to main worker"
echo "$ADMIN_SECRET" | npx wrangler secret put HUOZI_ADMIN_SECRET --config "$MAIN_WRANGLER_JSONC" >/dev/null
echo "$AUTH_SECRET"  | npx wrangler secret put HUOZI_AUTH_SECRET  --config "$MAIN_WRANGLER_JSONC" >/dev/null

# ── Deploy main worker ───────────────────────────────────────────────────
cyan "▸ Deploying main worker"
MAIN_DEPLOY_OUT="$(npx @opennextjs/cloudflare deploy -- --config "$MAIN_WRANGLER_JSONC" 2>&1 || true)"
MAIN_WORKER_URL="$(echo "$MAIN_DEPLOY_OUT" | grep -Eo 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -1 || true)"
if [[ -z "$MAIN_WORKER_URL" ]]; then
  red "✗ Couldn't extract main worker URL from deploy output"
  echo "$MAIN_DEPLOY_OUT"
  exit 1
fi
green "  Main worker: $MAIN_WORKER_URL"

# ── Set HUOZI_PUBLIC_BASE on cloud worker → main worker URL ──────────────
# Used for device-flow verification links + public share URLs minted by
# huozi_share. Now that we know where the UI lives, point cloud at it.
cyan "▸ Pointing HUOZI_PUBLIC_BASE on cloud → $MAIN_WORKER_URL"
echo "$MAIN_WORKER_URL" | npx wrangler secret put HUOZI_PUBLIC_BASE --config "$CLOUD_WRANGLER_TOML" >/dev/null

# ╔════════════════════════════════════════════════════════════════════╗
# ║  STAGE 3: Bootstrap api_key + smoke tests                           ║
# ╚════════════════════════════════════════════════════════════════════╝

# ── Mint the first admin api_key ─────────────────────────────────────────
cyan "▸ Minting first admin api_key"
MINT_BODY=$(cat <<JSON
{
  "workspace_id": "ws_$WORKSPACE_SLUG",
  "principal_id": "$ADMIN_USER_ID",
  "principal_type": "user",
  "ttl_seconds": null,
  "name": "[edge-admin] bootstrap"
}
JSON
)
MINT_OUT="$(curl -sS -X POST "$CLOUD_WORKER_URL/admin/mint-key" \
  -H "X-Admin-Secret: $ADMIN_SECRET" \
  -H "Content-Type: application/json" \
  -d "$MINT_BODY" || true)"
ADMIN_API_KEY="$(echo "$MINT_OUT" | jq -r '.api_key // empty' 2>/dev/null || true)"
if [[ -z "$ADMIN_API_KEY" ]]; then
  red "✗ mint-key failed. Raw response:"
  echo "$MINT_OUT" | head -10
  exit 1
fi

# ── Smoke test 1: huozi_whoami via MCP on cloud worker ───────────────────
cyan "▸ Smoke test: huozi_whoami over MCP (cloud worker)"
WHOAMI_OUT="$(curl -sS -X POST "$CLOUD_WORKER_URL/mcp" \
  -H "Authorization: Bearer $ADMIN_API_KEY" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json, text/event-stream" \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"huozi_whoami","arguments":{}}}')"
WHOAMI_ROLE="$(echo "$WHOAMI_OUT" | jq -r '.result.structuredContent.workspace.role // empty')"
if [[ "$WHOAMI_ROLE" != "owner" ]]; then
  red "✗ whoami did not report role=owner. Raw response:"
  echo "$WHOAMI_OUT"
  exit 1
fi
green "  ✓ MCP/cloud → role=owner"

# ── Smoke test 2: main worker reachable + middleware behaving ────────────
cyan "▸ Smoke test: main worker /connect (paste-key page)"
MAIN_HTTP_CODE="$(curl -sS -o /dev/null -w "%{http_code}" "$MAIN_WORKER_URL/connect" || true)"
if [[ "$MAIN_HTTP_CODE" != "200" ]]; then
  red "✗ Main worker /connect returned $MAIN_HTTP_CODE (expected 200)"
  exit 1
fi
green "  ✓ Main worker /connect → 200"

# ── Persist env file for local dev ───────────────────────────────────────
# This file lets you run `npm run dev` against the deployed Edge stack
# (e.g. for testing the UI changes against real D1 / R2). The hosted
# main worker is the canonical UI; this is just for local iteration.
cat > "$ENV_FILE" <<EOF
# scripts/edge-deploy.sh — generated $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source this to run Next.js locally against the deployed Edge stack:
#   set -a; source .huozi-edge.env; set +a
#   npm run dev
HUOZI_EDITION=edge
HUOZI_CLOUD_URL=$CLOUD_WORKER_URL
HUOZI_ADMIN_SECRET=$ADMIN_SECRET
HUOZI_AUTH_SECRET=$AUTH_SECRET
HUOZI_EDGE_WORKSPACE_SLUG=$WORKSPACE_SLUG
HUOZI_EDGE_WORKSPACE_NAME=$WORKSPACE_NAME

# Bootstrap api_key — paste into /workspace/connect on first visit.
# (Sensitive — do not commit. Regenerate via scripts/edge-deploy.sh.)
HUOZI_BOOTSTRAP_API_KEY=$ADMIN_API_KEY
EOF
chmod 600 "$ENV_FILE"

# ── Summary ──────────────────────────────────────────────────────────────
cat <<SUMMARY

$(green "════════ Edge deploy complete ════════")
  Main worker (UI):    $MAIN_WORKER_URL
  Cloud worker (API):  $CLOUD_WORKER_URL
  D1 db:               $D1_NAME ($D1_ID)
  R2 bucket:           $R2_NAME
  Workspace:           $WORKSPACE_SLUG  →  ws_$WORKSPACE_SLUG (UUID $WORKSPACE_UUID)
  Service binding:     $MAIN_WORKER_NAME.CLOUD → $CLOUD_WORKER_NAME
  Admin api_key:       $ADMIN_API_KEY

  Env file:            $ENV_FILE  (chmod 600, gitignored)

$(cyan "Next steps:")
  1. Visit the deployed UI:
       $MAIN_WORKER_URL/workspace/connect
     and paste:
       $ADMIN_API_KEY
  2. (Optional) Run Next.js locally against this stack:
       set -a; source .huozi-edge.env; set +a
       npm run dev

$(cyan "Tear down:")
  scripts/edge-teardown.sh

SUMMARY
