#!/usr/bin/env bash
#
# scripts/edge-deploy-test.sh
#
# One-shot deploy of the huozi-edge reference instance into the user's
# Cloudflare account. Fixed resource names — there's exactly one Edge
# test deploy per CF account. Re-running is idempotent (D1 / R2 reuse
# existing rows; secret is rotated; worker is redeployed).
#
# Provisions:
#   - Worker:  huozi-edge          (workers.dev URL, no custom domain)
#   - D1:      huozi-edge-db
#   - R2:      huozi-edge-blobs
#   - DOs:     scoped to the Worker (HuoziWorkspaceDO, HuoziSessionDO)
#   - Secret:  HUOZI_ADMIN_SECRET (random; saved to .huozi-edge.env)
#   - Workspace row (slug = $WORKSPACE_SLUG, owner = "admin", new UUID)
#   - First admin api_key against ws_<workspace_slug>
#
# WORKSPACE_SLUG is the *inside* slug — it's the value api_keys.workspace_id
# uses (`ws_<slug>`) and what HUOZI_EDGE_WORKSPACE_SLUG must match. Default
# is "default"; override with the env var if you want something else.
#
# After it finishes you'll get:
#   - The Worker URL  (https://huozi-edge.<acct>.workers.dev/mcp)
#   - The admin api_key to paste at /workspace/connect
#   - A .huozi-edge.env file with everything for `npm run dev` in Edge mode
#
# Usage:
#   scripts/edge-deploy-test.sh
#   WORKSPACE_SLUG=alice scripts/edge-deploy-test.sh
#
# Tear down: scripts/edge-deploy-test-teardown.sh
#

set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKER_DIR="$ROOT_DIR/packages/huozi-cloud"

WORKSPACE_SLUG="${WORKSPACE_SLUG:-default}"
WORKSPACE_NAME="${WORKSPACE_NAME:-huozi-edge}"
ADMIN_USER_ID="${ADMIN_USER_ID:-admin}"

if [[ ! "$WORKSPACE_SLUG" =~ ^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$ ]]; then
  echo "✗ WORKSPACE_SLUG must match /^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$/  (got: $WORKSPACE_SLUG)" >&2
  exit 1
fi

WORKER_NAME="huozi-edge"
D1_NAME="huozi-edge-db"
R2_NAME="huozi-edge-blobs"
WRANGLER_TOML="$WORKER_DIR/wrangler.edge.toml"
ENV_FILE="$ROOT_DIR/.huozi-edge.env"

cyan() { printf '\033[36m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
red() { printf '\033[31m%s\033[0m\n' "$*" >&2; }

# ── Preflight ────────────────────────────────────────────────────────────
cyan "▸ Preflight"
command -v node >/dev/null || { red "✗ node not in PATH"; exit 1; }
command -v npx >/dev/null || { red "✗ npx not in PATH"; exit 1; }
command -v jq >/dev/null || { red "✗ jq not in PATH (brew install jq)"; exit 1; }

cd "$WORKER_DIR"
npx wrangler whoami >/dev/null 2>&1 || {
  red "✗ wrangler not authenticated. Run \`npx wrangler login\` first."
  exit 1
}

# ── Build worker ─────────────────────────────────────────────────────────
cyan "▸ Building worker (tsc → dist/)"
npx tsc

# ── Generate test wrangler.toml ──────────────────────────────────────────
cyan "▸ Generating $(basename "$WRANGLER_TOML")"
cat > "$WRANGLER_TOML" <<EOF
# Auto-generated by scripts/edge-deploy-test.sh — DO NOT EDIT BY HAND.
# Tear down:  scripts/edge-deploy-test-teardown.sh
name = "$WORKER_NAME"
main = "dist/worker/index.js"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

# No custom domain — uses the workers.dev URL so we don't touch DNS.

[[r2_buckets]]
binding = "BLOBS"
bucket_name = "$R2_NAME"

[[d1_databases]]
binding = "DB"
database_name = "$D1_NAME"
database_id = "__FILLED_AFTER_CREATE__"

[[durable_objects.bindings]]
name = "WORKSPACE_DO"
class_name = "HuoziWorkspaceDO"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "HuoziSessionDO"

[[migrations]]
tag = "v1"
new_classes = ["HuoziWorkspaceDO", "HuoziSessionDO"]

[observability]
enabled = true
EOF

# ── Create / find D1 ─────────────────────────────────────────────────────
# Always look up via `d1 list` — covers both fresh creates and re-runs.
# (Parsing `d1 create` output is brittle: format differs between fresh
# success, "already exists" error, and various wrangler versions.)
cyan "▸ Creating D1 database $D1_NAME"
npx wrangler d1 create "$D1_NAME" 2>&1 | tail -3 || true
D1_ID="$(npx wrangler d1 list --json 2>/dev/null \
         | jq -r --arg n "$D1_NAME" '.[] | select(.name==$n) | .uuid' \
         | head -1 || true)"
if [[ -z "$D1_ID" ]]; then
  red "✗ Failed to create or find D1 $D1_NAME"
  exit 1
fi
green "  database_id = $D1_ID"
sed -i.bak "s|__FILLED_AFTER_CREATE__|$D1_ID|" "$WRANGLER_TOML" && rm -f "$WRANGLER_TOML.bak"

# ── Create R2 (idempotent) ───────────────────────────────────────────────
cyan "▸ Creating R2 bucket $R2_NAME"
npx wrangler r2 bucket create "$R2_NAME" 2>&1 | grep -v "already exists" || true

# ── Apply schema ─────────────────────────────────────────────────────────
cyan "▸ Applying D1 schema"
npx wrangler d1 execute "$D1_NAME" --remote \
  --config "$WRANGLER_TOML" \
  --file src/storage/cloudflare/schema.sql >/dev/null

# ── Seed users + workspace + membership for the Edge admin ───────────────
# Edge identity uses the literal "admin" as both userId and ownerId; we
# need at least one users row + one workspaces row + one workspace_members
# row before the Worker's mint-key validators will accept the request.
#
# Schema notes:
#   - workspaces.id is a UUID (matches the legacy cloud_workspaces.id shape)
#   - api_keys.workspace_id and DO routing use the string `ws_<slug>` form;
#     the worker JOINs the two via workspaces.slug. So we generate a fresh
#     UUID for workspaces.id, but bind api_keys.workspace_id to ws_<slug>.
cyan "▸ Seeding admin user / workspace / membership rows"
NOW_MS=$(node -e 'process.stdout.write(String(Date.now()))')
WORKSPACE_UUID=$(node -e 'process.stdout.write(require("crypto").randomUUID())')
SEED_SQL=$(cat <<SQL
INSERT OR IGNORE INTO users (id, email, display_name, created_at)
  VALUES ('$ADMIN_USER_ID', 'admin@edge.local', 'Edge Admin', $NOW_MS);
INSERT OR IGNORE INTO workspaces (id, slug, name, owner_id, created_at)
  VALUES ('$WORKSPACE_UUID', '$WORKSPACE_SLUG', '$WORKSPACE_NAME', '$ADMIN_USER_ID', $NOW_MS);
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, joined_at)
  VALUES ('$WORKSPACE_UUID', '$ADMIN_USER_ID', 'owner', $NOW_MS);
SQL
)
npx wrangler d1 execute "$D1_NAME" --remote \
  --config "$WRANGLER_TOML" \
  --command "$SEED_SQL" >/dev/null

# ── Generate + push the admin secret ─────────────────────────────────────
cyan "▸ Generating HUOZI_ADMIN_SECRET (32 hex bytes)"
ADMIN_SECRET="$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')"
echo "$ADMIN_SECRET" | npx wrangler secret put HUOZI_ADMIN_SECRET \
  --config "$WRANGLER_TOML" >/dev/null

# ── Deploy the worker ────────────────────────────────────────────────────
cyan "▸ Deploying worker"
DEPLOY_OUT="$(npx wrangler deploy --config "$WRANGLER_TOML" 2>&1 || true)"
WORKER_URL="$(echo "$DEPLOY_OUT" | grep -Eo 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -1 || true)"
if [[ -z "$WORKER_URL" ]]; then
  red "✗ Couldn't extract worker URL from deploy output"
  echo "$DEPLOY_OUT"
  exit 1
fi
green "  $WORKER_URL"

# ── Set HUOZI_PUBLIC_BASE so huozi_share URLs point somewhere reachable ──
# Override via PUBLIC_BASE=… if you're hosting Next.js on a different host.
# Default = the Next.js dev server (localhost:3000) so the local dev loop
# Just Works™. For a real deploy, set this to your Next.js public URL.
PUBLIC_BASE="${PUBLIC_BASE:-http://localhost:3000}"
cyan "▸ Setting HUOZI_PUBLIC_BASE=$PUBLIC_BASE on the worker"
echo "$PUBLIC_BASE" | npx wrangler secret put HUOZI_PUBLIC_BASE \
  --config "$WRANGLER_TOML" >/dev/null
# Plain env vars do work too (vars.HUOZI_PUBLIC_BASE in wrangler.toml), but
# secrets keep wrangler.toml free of host-specific config — easier to share
# the toml as a template.

# ── Mint the first admin api_key ─────────────────────────────────────────
cyan "▸ Minting first admin api_key"
MINT_BODY=$(cat <<JSON
{
  "workspace_id": "ws_$WORKSPACE_SLUG",
  "principal_id": "$ADMIN_USER_ID",
  "principal_type": "user",
  "ttl_seconds": null,
  "name": "[edge-admin] bootstrap"
}
JSON
)
MINT_OUT="$(curl -sS -X POST "$WORKER_URL/admin/mint-key" \
  -H "X-Admin-Secret: $ADMIN_SECRET" \
  -H "Content-Type: application/json" \
  -d "$MINT_BODY" || true)"
ADMIN_API_KEY="$(echo "$MINT_OUT" | jq -r '.api_key // empty' 2>/dev/null || true)"
if [[ -z "$ADMIN_API_KEY" ]]; then
  red "✗ mint-key failed. Raw response:"
  echo "$MINT_OUT" | head -10
  exit 1
fi

# ── Smoke test: huozi_whoami via MCP ─────────────────────────────────────
cyan "▸ Smoke test: huozi_whoami over MCP"
WHOAMI_OUT="$(curl -sS -X POST "$WORKER_URL/mcp" \
  -H "Authorization: Bearer $ADMIN_API_KEY" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json, text/event-stream" \
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"huozi_whoami","arguments":{}}}')"
WHOAMI_ROLE="$(echo "$WHOAMI_OUT" | jq -r '.result.structuredContent.workspace.role // empty')"
if [[ "$WHOAMI_ROLE" != "owner" ]]; then
  red "✗ whoami did not report role=owner. Raw response:"
  echo "$WHOAMI_OUT"
  exit 1
fi
green "  ✓ whoami → role=owner"

# ── Persist env file for the Next.js app ─────────────────────────────────
cat > "$ENV_FILE" <<EOF
# scripts/edge-deploy-test.sh — generated $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source this when starting the Next.js Edge build:
#   set -a; source .huozi-edge.env; set +a
#   npm run dev
HUOZI_EDITION=edge
HUOZI_CLOUD_URL=$WORKER_URL
HUOZI_ADMIN_SECRET=$ADMIN_SECRET
HUOZI_AUTH_SECRET=$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')
HUOZI_EDGE_WORKSPACE_SLUG=$WORKSPACE_SLUG
HUOZI_EDGE_WORKSPACE_NAME=$WORKSPACE_NAME

# Bootstrap api_key — paste into /workspace/connect on first visit.
# (Sensitive — do not commit. Regenerate via scripts/edge-deploy-test.sh.)
HUOZI_BOOTSTRAP_API_KEY=$ADMIN_API_KEY
EOF
chmod 600 "$ENV_FILE"

# ── Summary ──────────────────────────────────────────────────────────────
cat <<SUMMARY

$(green "════════ Edge deploy complete ════════")
  Worker URL:      $WORKER_URL
  Worker name:     $WORKER_NAME
  D1 db:           $D1_NAME ($D1_ID)
  R2 bucket:       $R2_NAME
  Workspace slug:  $WORKSPACE_SLUG  →  ws_$WORKSPACE_SLUG (UUID $WORKSPACE_UUID)
  Admin api_key:   $ADMIN_API_KEY

  Env file:        $ENV_FILE  (chmod 600, gitignored)

$(cyan "Next steps:")
  1. Run the Next.js app in Edge mode pointing at this worker:
       set -a; source .huozi-edge.env; set +a
       npm run dev
  2. Visit http://localhost:3000/workspace/connect and paste:
       $ADMIN_API_KEY

$(cyan "Tear down:")
  scripts/edge-deploy-test-teardown.sh

SUMMARY
