/**
 * /authorize/done — branded "授权完成" landing page.
 *
 * The browser arrives here AFTER the consent form has successfully
 * minted an authorization code on the worker. We render a confirmation
 * panel for ~3 seconds, then auto-redirect to the localhost callback
 * URL the OAuth client (Claude Code, Cursor, ...) is listening on.
 *
 * Why this page exists:
 *   - Without it, the last thing the user sees is whatever blank HTML
 *     Claude Code's local HTTP server hands back ("You can close this
 *     window. Return to Claude Code."). That page has no branding,
 *     no workspace context, no link back to /workspace.
 *   - We can't avoid the localhost hop (PKCE requires the code reach
 *     the calling process), but we CAN insert a 3-second branded step
 *     in front of it so the perceived completion state is huozi's,
 *     not the OAuth client's.
 *
 * Security notes on `?to=`:
 *   - The `to` URL was generated by the worker's /admin/oauth/approve
 *     handler, which only emits a URL pointing at the redirect_uri
 *     the client registered (and re-validated at /oauth/authorize).
 *     So the URL is trustworthy in the happy path.
 *   - As an extra safety net, we still hard-restrict the protocol to
 *     http/https on the client side before location.assign(). Defends
 *     against `javascript:` if any future bug let one slip through.
 */

import type { Metadata } from "next";
import { AuthorizeDoneView } from "./done-view";

export const metadata: Metadata = {
  title: "Authorized — huozi",
  robots: { index: false, follow: false },
};

interface Props {
  searchParams?: Promise<{
    to?: string;
    client?: string;
    workspace?: string;
  }>;
}

export default async function AuthorizeDonePage({ searchParams }: Props) {
  const params = (await searchParams) ?? {};
  return (
    <AuthorizeDoneView
      to={params.to ?? ""}
      clientName={params.client ?? "Agent"}
      workspaceName={params.workspace ?? "your workspace"}
    />
  );
}
